#!/bin/bash

# Convert a given video to a gif w/ optional start and end time
# Works w/ WEBM, MP4, and MOV input formats (at least)



STARTING_DIR="$PWD"

FILE_PATH="$(realpath "${1}")"
# https://code-maven.com/bash-absolute-path
FILEPATH_NO_EXT="${FILE_PATH%.*}"
EXT="${FILE_PATH##*.}"
FILENAME=$(basename "${FILE_PATH}") # includes extension

FILENAME_NO_EXT=$(basename "${FILE_PATH}" "."${EXT})
# https://unix.stackexchange.com/questions/313017/bash-function-splitting-name-and-extension-of-a-file
# https://linuxhandbook.com/basename/
FILE_DIR_OG=$(dirname "${FILE_PATH}")
# https://linuxhandbook.com/dirname/

NEW_EXT="gif"
# put timestamps in output filename
if [[ $# == 2 ]];
then
  FILEPATH_OUT="${FILEPATH_NO_EXT}_${2}s-.${NEW_EXT}"
elif [[ $# == 3 ]];
then
  FILEPATH_OUT="${FILEPATH_NO_EXT}_${2}-${3}s.${NEW_EXT}"
else
  FILEPATH_OUT="${FILEPATH_NO_EXT}.${NEW_EXT}"
fi

# Validate input path
if [[ -e "${FILE_PATH}" ]];
then
  :
else
  printf "\nSpecified file cannot be found.\n"
  exit 1
fi

# Check for existence of output file before attempting conversion.
# ffmpeg has this check, but it requires the rest of the verbose output
# (which is suppressed below)
# Check for both resolvable path and broken symlink # https://unix.stackexchange.com/a/550837
if [[ -e "${FILEPATH_OUT}" ]] || [[ -h "${FILEPATH_OUT}" ]];
then
  printf "\nTarget file exists. Overwrite? [Y/N]\n"
  read -p ">" answer
  if [ "$answer" == "y" -o "$answer" == "Y" ];
  then
    rm "${FILEPATH_OUT}"
  else
    printf "Exiting\n"
    exit 1
  fi
fi

if [ $# -gt 3 ];
then
  printf "\nExpected one to three arguments - filename, start time (optional), and end time (optional)\n"
  exit 1
fi

printf "\nAttempting to convert to gif..."
if [[ $# == 1 ]]; # one arg
then
  ffmpeg -i "${FILE_PATH}" \
  -vf "fps=10,scale=320:-1:flags=lanczos,split[s0][s1];[s0]palettegen[p];[s1][p]paletteuse" \
  -loop 0 "${FILEPATH_OUT}" &> /dev/null
  # https://superuser.com/questions/556029/how-do-i-convert-a-video-to-gif-using-ffmpeg-with-reasonable-quality
  # https://www.ubuntubuzz.com/2017/08/convert-mp4-webm-video-to-gif-using-ffmpeg.html
elif [[ $# == 2 ]]; # two args
then
  ffmpeg -ss ${2} -i "${FILE_PATH}" \
  -vf "fps=10,scale=320:-1:flags=lanczos,split[s0][s1];[s0]palettegen[p];[s1][p]paletteuse" \
  -loop 0 "${FILEPATH_OUT}" &> /dev/null
elif [[ $# == 3 ]]; # three args
then
  # have to convert from end time to duration ffmpeg expects
  START_TIME=$2
  END_TIME=$3
  # DURATION="$((END_TIME - START_TIME))"
  # https://unix.stackexchange.com/questions/232384/argument-string-to-integer-in-bash
  # check for negative number
  # if [ ${DURATION} -lt 1 ];
  # then
  #   printf "FAIL\nEnd time must be greater than start time\n"
  #   exit 1
  # else
  #   ffmpeg -ss ${2} -t ${DURATION} -i "${FILE_PATH}" \
  #   -vf "fps=10,scale=320:-1:flags=lanczos,split[s0][s1];[s0]palettegen[p];[s1][p]paletteuse" \
  #   -loop 0 "${FILEPATH_OUT}" &> /dev/null
  # fi
  ffmpeg -ss ${2} -i "${FILE_PATH}" -to ${END_TIME} \
  -vf "fps=10,scale=320:-1:flags=lanczos,split[s0][s1];[s0]palettegen[p];[s1][p]paletteuse" \
  -loop 0 "${FILEPATH_OUT}" &> /dev/null
fi

# Test if conversion was successful since ffmpeg output suppressed.
FFMPEG_RETURN=$? # gets return value of last command executed.
if [ ${FFMPEG_RETURN} == 0 ]
then
  printf "SUCCESS\n"
  # Open gif so user can confirm valid output file.
	xdg-open 2>/dev/null "${FILEPATH_OUT}"
else
  printf "FAIL\n"
  exit 1
fi
