#!/bin/bash

FILE_PATH="$(realpath "${1}")"

DEFAULT=False
LONGSTAMP=${2:-$DEFAULT}

printf "import idevice_media_offload.date_compare as dc ; dc.datestamp_all('%s', $LONGSTAMP)", "$FILE_PATH" | python



# https://stackoverflow.com/questions/21934880/run-function-from-the-command-line-and-pass-arguments-to-function
# https://stackoverflow.com/questions/4139436/how-to-call-python-functions-when-running-from-terminal
# https://stackoverflow.com/questions/2013547/assigning-default-values-to-shell-variables-with-a-single-command-in-bash
