#!/bin/bash


if [ $# -ne 2 ];
then
  printf "\nExpected two arguments - filename and comment to add\n"
  exit 1
fi


FILE_PATH="$(realpath "${1}")"
COMMENT="${2}"
# Validate input path
if [[ -e "${FILE_PATH}" ]];
then
  :
else
  printf "\nSpecified file cannot be found.\n"
  exit 1
fi


printf "\nAttempting to write EXIF comment..."
exiftool -Comment="${COMMENT}" "${FILE_PATH}" &> /dev/null
EXIF_RETURN=$?
OG_BU_PATH="${FILE_PATH}_original"

if [[ ${EXIF_RETURN} == 0 ]];
then
	if [[ -f "${OG_BU_PATH}" ]];
	then
		rm "${OG_BU_PATH}"
		printf "SUCCESS\n"
	else
		printf "FAIL\nCan't find '_original' file.\n"
		exit 1
	fi
else
	printf "FAIL\nCall to exiftool unsuccessful.\n"
	exit 1
fi
